<a href="https://colab.research.google.com/github/nomanGondal/LogisticRegression/blob/main/LogisticRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [59]:
#Logistic Regression
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report,confusion_matrix, accuracy_score,recall_score,precision_score
from sklearn.preprocessing import StandardScaler,LabelEncoder,MinMaxScaler

In [3]:
df=sns.load_dataset('titanic')
df.head()

   survived  pclass     sex   age  ...  deck  embark_town  alive  alone
0         0       3    male  22.0  ...   NaN  Southampton     no  False
1         1       1  female  38.0  ...     C    Cherbourg    yes  False
2         1       3  female  26.0  ...   NaN  Southampton    yes   True
3         1       1  female  35.0  ...     C  Southampton    yes  False
4         0       3    male  35.0  ...   NaN  Southampton     no   True

[5 rows x 15 columns]

In [4]:
Y=df['survived']
X=df.drop('survived',axis=1)
X.head()

   pclass     sex   age  sibsp  ...  deck  embark_town alive  alone
0       3    male  22.0      1  ...   NaN  Southampton    no  False
1       1  female  38.0      1  ...     C    Cherbourg   yes  False
2       3  female  26.0      0  ...   NaN  Southampton   yes   True
3       1  female  35.0      1  ...     C  Southampton   yes  False
4       3    male  35.0      0  ...   NaN  Southampton    no   True

[5 rows x 14 columns]

In [8]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   pclass       891 non-null    int64
 1   sex          891 non-null    int64
 2   age          714 non-null    float64
 3   sibsp        891 non-null    int64
 4   parch        891 non-null    int64
 5   fare         891 non-null    float64
 6   embarked     889 non-null    object
 7   class        891 non-null    category
 8   who          891 non-null    object
 9   adult_male   891 non-null    bool
 10  deck         203 non-null    category
 11  embark_town  889 non-null    object
 12  alive        891 non-null    object
 13  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(4)
memory usage: 73.7+ KB

In [12]:
df.drop(['survived'],axis=1,inplace=True)
df.head()

   pclass     sex   age  sibsp  ...  adult_male  embark_town alive  alone
0       3    male  22.0      1  ...        True  Southampton    no  False
1       1  female  38.0      1  ...       False    Cherbourg   yes  False
2       3  female  26.0      0  ...       False  Southampton   yes   True
3       1  female  35.0      1  ...       False  Southampton   yes  False
4       3    male  35.0      0  ...        True  Southampton    no   True

[5 rows x 13 columns]

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   pclass       891 non-null    int64
 1   sex          891 non-null    object
 2   age          714 non-null    float64
 3   sibsp        891 non-null    int64
 4   parch        891 non-null    int64
 5   fare         891 non-null    float64
 6   embarked     889 non-null    object
 7   class        891 non-null    category
 8   who          891 non-null    object
 9   adult_male   891 non-null    bool
 10  embark_town  889 non-null    object
 11  alive        891 non-null    object
 12  alone        891 non-null    bool
dtypes: bool(2), category(1), float64(2), int64(3), object(5)
memory usage: 72.5+ KB

In [15]:
df['age'].fillna(df['age'].median(),inplace=True)

/tmp/ipython-input-2790788646.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['age'].fillna(df['age'].median(),inplace=True)

In [ ]:
df['age'].fillna(df['age'].median(),inplace=True)

In [23]:
df.drop(['embarked'],axis=1,inplace=True)

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   pclass      891 non-null    int64
 1   sex         891 non-null    object
 2   age         891 non-null    float64
 3   sibsp       891 non-null    int64
 4   parch       891 non-null    int64
 5   fare        891 non-null    float64
 6   class       891 non-null    category
 7   who         891 non-null    object
 8   adult_male  891 non-null    bool
 9   alive       891 non-null    object
 10  alone       891 non-null    bool
dtypes: bool(2), category(1), float64(2), int64(3), object(3)
memory usage: 58.6+ KB

In [46]:
for col in df.columns:
    if df[col].dtype == 'object' or df[col].dtype == 'category':
        le = LabelEncoder()   # use a variable like 'le'
        df[col] = le.fit_transform(df[col].astype(str))

In [47]:
df.head()

   pclass  sex   age  sibsp  parch  ...  class  who  adult_male  alive  alone
0       3    1  22.0      1      0  ...      2    1        True      0  False
1       1    0  38.0      1      0  ...      0    2       False      1  False
2       3    0  26.0      0      0  ...      2    2       False      1   True
3       1    0  35.0      1      0  ...      0    2       False      1  False
4       3    1  35.0      0      0  ...      2    1        True      0   True

[5 rows x 11 columns]

In [48]:
X=df

In [51]:
x_train , x_test , y_train , y_test = train_test_split(X,Y,test_size=0.2)

In [75]:
class MyLogisticRegression:
    def __init__(self, lr=0.01, n_iters=1000):
        self.lr = lr                # learning rate
        self.n_iters = n_iters      # number of iterations
        self.weights = None
        self.bias = None

    def sigmoid(self, z):
     z = np.array(z, dtype=np.float64)
     return 1 / (1 + np.exp(-z))
    def fit(self, X, y):
        """Train the model using Gradient Descent"""
        X = np.array(X, dtype=np.float64)
        y = np.array(y, dtype=np.float64)
        n_samples, n_features = X.shape
        self.weights = np.zeros(n_features)
        self.bias = 0

        # Gradient Descent
        for _ in range(self.n_iters):
            # Linear prediction
            linear_model = np.dot(X, self.weights) + self.bias
            # Apply sigmoid
            y_pred = self.sigmoid(linear_model)

            # Gradients
            dw = (1 / n_samples) * np.dot(X.T, (y_pred - y))
            db = (1 / n_samples) * np.sum(y_pred - y)

            # Update parameters
            self.weights -= self.lr * dw
            self.bias -= self.lr * db

    def predict_proba(self, X):
        """Return predicted probabilities"""
        linear_model = np.dot(X, self.weights) + self.bias
        return self.sigmoid(linear_model)

    def predict(self, X):
        """Return class labels (0 or 1)"""
        y_pred_prob = self.predict_proba(X)
        return np.where(y_pred_prob >= 0.5, 1, 0)

In [76]:
model=MyLogisticRegression(lr=0.1, n_iters=1000)

In [77]:
model.fit(x_train,y_train)

In [78]:
y_pred=model.predict(x_test)

In [57]:
#evaluation metrics
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       117
           1       1.00      1.00      1.00        62

    accuracy                           1.00       179
   macro avg       1.00      1.00      1.00       179
weighted avg       1.00      1.00      1.00       179

In [79]:
print('confusion matrix',confusion_matrix(y_test,y_pred))
print('accuracy score ',accuracy_score(y_test,y_pred))
print('Recall score' , recall_score(y_test,y_pred))
print('Precision score' , precision_score(y_test,y_pred))

confusion matrix [[  3 114]
 [  0  62]]
accuracy score  0.36312849162011174
Recall score 1.0
Precision score 0.3522727272727273